methodsMapping = {
    "address": {"datatype":"string", "keys": ["address"], "method": "address"},
    "administrative_unit": {"datatype":"string", "keys": ["administrative_unit"], "method": "administrative_unit"},
    "am_or_pm": {"datatype":"string", "keys": ["am_or_pm"], "method": "am_pm"},
    "android_platform_token": {"datatype":"string", "keys": ["android_platform_token", "android"], "method": "android_platform_token"},
    # base64: base64.b64encode(f.text(max_nb_chars=15).encode())---->import base64
    "hh:mm:ss:ms": { "datatype":"string", "keys":["time"], "method": "time", "args": "%H:%M:%S"},
    "0/1": {"datatype":"number", "keys": ["bit", "0or1", "1or0"] , "method": "random_int", "args": [0, 1]},
    # objectID:bson.objectid.ObjectId()--->import bson
    "serial-id": {"datatype":"string", "method": "random_int", "args": [100, 999]},
    "amount": {"datatype":"number", "method": "random_int", "args": [1000, 9999999]},
    "empid": {"datatype":"string", "keys": ["emp", "employee", "employeeid", "employee_id", "employeeId"] , "method": "random_int", "args": [100, 999]},
    "salary": {"datatype":"number", "keys":["salary"], "method": "random_int", "args": [10000, 99999]},
    "profession": {"datatype":"string", "keys":["profession", "job"], "method": "job"},
    "randomnumber": {"datatype":"number", "method": "random_int", "args": [1, 99999]},
    "children": {"datatype":"number", "method": "random_int", "args": [1, 4]},
    "age": {"datatype":"number", "method": "random_int", "args": [10, 80]},
    "weight": {"datatype":"number", "method": "random_int", "args": [10, 180]},
    "releaseyear": {"datatype":"number", "method": "year"},
    "phoneno": {"datatype":"string", "keys":["phone", "mobile", "contactno"], "method": "phone_number"},
    "email": {"datatype":"string", "method": "email"},
    "gender-abbr": {"datatype":"string", "keys":["gender"], "method": "passport_gender"},
    "lastname": {"datatype": "string","keys":["lastname"], "method": "last_name"},
    "firstname": {"datatype": "string", "keys":["firstname"], "method": "first_name"},
    "zipcode": {"datatype": "string", "method": "zipcode"},
    "city": {"datatype": "string", "keys":["city", "location"], "method": "city"},
    "state": {"datatype": "string", "method": "state"},
    "street": {"datatype": "string", "method": "street_name"},
    "state-abbr": {"datatype": "string", "method": "state_abbr"},
    "country-code": {"datatype": "string", "keys":["country_code", "countrycode"], "method": "country_code"},
    "country": {"datatype": "string", "keys":["country"], "method": "country"},
    "hex": {"datatype": "string", "keys":["color"], "method": "color"},
    "colorname": {"datatype": "string", "method": "color_name"},
    "rgb": {"datatype": "string", "method": "rgb_color"},
    "word": {"datatype": "string", "method": "word"},
    "sentence": {"datatype": "string", "format":"long", "method": "sentence"},
    "paragraph": {"datatype": "string", "format":"long", "method": "paragraph"},
    "letter": {"datatype": "string", "format":"long", "method": "random_letter"},
    "emoji": {"datatype": "string", "method": "emoji"},
    "sha-1": {"datatype":"string", "keys":["sha1"], "method": "sha1"},
    "sha-256": {"datatype":"string", "keys":["sha265"],"method": "sha256"},
    "imageurl": {"datatype": "string", "method": "image_url"},
    "password": {"datatype": "string", "method": "password"},
    "ipv4-address": {"datatype": "string", "keys":["ipv4"], "method": "ipv4"},
    "ipv6-address": {"datatype": "string", "keys": ["ipv6"], "method": "ipv6"},
    "mac-address": {"datatype": "string", "kesy":["mac_address"], "method": "mac_address"},
    "useragent": {"datatype": "string", "method": "user_agent"},
    "username": {"datatype": "string", "method": "user_name"},
    "name": {"datatype": "string", "method": "user_name"},
    "latitude": {"datatype":"decimal", "method": "latitude", "keys":["latitude"], },
    "longitude": {"datatype":"decimal", "keys": ["longitude"], "method": "longitude"},
    "cardno": {"datatype": "string", "keys":["credit_number", "cardno"], "method": "credit_card_number"},
    "company": {"datatype": "string", "keys":["company"], "method": "company"},
    # Creditcard-company:credit_card_provider.split(' ')[0]
    "expiration-date": {"datatype": "string", "keys":["credit_card_date", "credit_card_expire"], "method": "credit_card_expire"},
    "am/pm": {"datatype": "string","method": "am_pm"},
    "dd-mm-yyyy": {"datatype": "string", "keys":["dd/mm/yyyy", "dob"], "method": "date", "args": ["%d-%m-%Y"]},
    "mm-dd-yyyy": {"datatype": "string", "keys":["mm/dd/yyyy"], "method": "date", "args": ["%m-%d-%Y"]},
    "yyyy-mm-dd": {"datatype": "string", "keys":["yyyy/mm/dd"], "method": "date", "args": ["%Y-%m-%d"]},
    "day-abbr": {"datatype": "string", "method": "day_of_month"},
    # ()[:3]
    # "dd/mm/yyyy": {"datatype": "string", "method": "date", "args": ["%d/%m/%Y"]},
    "domain_name":{"datatype": "string", "Keys": ['domain_name', "website"], "method": "domain_name", "args":[]},
    "day": {"datatype": "string", "keys": ["day"], "method": "day_of_month"},
    "month": {"datatype": "string", "method": "month"},
    "month_abbr": {"datatype": "string", "method": "month_name"},
    "year": {"datatype": "string", "method": "year"},
    "hh:mm:ss": {"datatype": "string", "method": "time"},
    "hh:mm:ss:ms": { "datatype": "string", "method": "time", "args": ["%H:%M:%S:%S"]},
    "timezone": {"datatype": "string", "method": "timezone"},
    "boolean": {"datatype": "boolean", "method": "boolean"},
    "digit": {"datatype": "number", "keys":["digit"], "method": "random_digit"},
    "float": {"datatype": "float", "keys":["float", "double"], "method": "pyfloat"},
    "int": {"datatype": "number", "keys":["digit"], "method": "pyint"},
    "integer": {"datatype": "number", "method": "pyint"},
    "string": {"datatype": "string", "method": "text", "args": [15]},
    "number": {"datatype": "number","method": "pyint"},
    "title": {"datatype": "string", "method": "sentence"},
    "continent": {"datatype": "string", "method": "continent"},
    "schoolClass":{"datatype":"number", "method": "random_int", "args": [1, 12]},
    "barcode": {"datatype": "string", "keys":["barcode"], "method": "ean"},
    "file_extension": {"datatype": "string", "keys":["file_extension"], "method": "file_extension"},
    "file_name": {"datatype": "string", "keys":["file_name"], "method": "file_name"},
    "file_path": {"datatype": "string", "keys":["file_path"], "method": "file_path"},
    "filefox": {"datatype": "string", "keys":[], "method": "filefox"},
    "language_name": {"datatype": "string", "keys":["language"], "method": "language_name"},
    "processor": {"datatype": "string", "keys":["processor"], "method": ["linux_processor", "mac_processor"]},
    "mime_type": {"datatype": "string", "keys":["mime_type", "mime"], "method": "mime_type"},
    "postalcode": {"datatype": "string", "keys": ["post", "postalcode", "postcode"], "method": "postalcode"},
    "pricetag": {"datatype": "string", "keys": ["pricetag", "price"], "method": "pricetag"}
}

# methodsMapping=dict((k.lower(),v) for k,v in methodsMapping.items())